SELECT p.PLATAFORMA, COUNT(tp.ID_TITOLS_PLATAFORMA) AS cantidad_contenido_accion
FROM PLATAFORMA p
JOIN TITOLS_PLATAFORMA tp ON p.ID = tp.ID_PLATAFORMA
JOIN TITOLS t ON tp.ID_TITOLS_PLATAFORMA = t.ID
JOIN TITOLS_GENERE tg ON t.ID = tg.ID_TITOLS
JOIN GENERES g ON tg.ID_GENERE = g.ID
WHERE g.GENERE = 'action'
GROUP BY p.PLATAFORMA
ORDER BY COUNT(tp.ID_PLATAFORMA) ASC
LIMIT 7;