SELECT 
    p.PLATAFORMA,
    SUM(CASE WHEN t.TIPUS = 'SHOW' THEN 1 ELSE 0 END) AS cantidad_series,
    SUM(CASE WHEN t.TIPUS = 'MOVIE' THEN 1 ELSE 0 END) AS cantidad_peliculas
FROM 
    PLATAFORMA p
JOIN 
    TITOLS_PLATAFORMA tp ON p.ID = tp.ID_PLATAFORMA
JOIN 
    TITOLS t ON tp.ID_TITOLS_PLATAFORMA = t.ID
GROUP BY 
    p.PLATAFORMA;